### ISSUE TITLE
Unnecessary eval of certain types.

### ISSUE THREAD

**Issue by nedzadarek** [greggirwin/red-formatting#1]
Composite tries to `eval` certain types, like `string!`:
```
composite {:("foo"):}
; == " *** Error: no-value Where: foo *** "
foo: 'baz
; == baz
composite {:("foo"):}
; == "baz"
```
Talk: https://gitter.im/red/help?at=5b2b82f15862c35f47ba7ad8

**Comment by greggirwin** [comment]
Fixed this some time back, but haven't been back into it to push. Done now.
